language: python
cache: pip
python:
  - "2.7"
# command to install dependencies
install: "pip install -r .travis-ci.d/requirements.txt"
# command to run tests
script:
  - export PYTHONPATH=${PWD%/*}
  - echo $PYTHONPATH
  - .travis-ci.d/run-unittests.sh
after_success:
  - codecov